-- Account-level billing summary sourced from QuickBooks.
alter table public.client_accounts
  add column if not exists balance_due_cents bigint not null default 0,
  add column if not exists balance_currency text not null default 'USD',
  add column if not exists quickbooks_payment_url text,
  add column if not exists balance_due_updated_at timestamptz;

comment on column public.client_accounts.balance_due_cents is
  'Current outstanding balance from QuickBooks, stored in the smallest currency unit.';
comment on column public.client_accounts.quickbooks_payment_url is
  'Payment link generated by QuickBooks for this account.';
